# -*- Makefile -*-
SPATH=../src
IPATH=../include
#RPATH=..
OBJS = $(SPATH)/compute_forces.o  $(SPATH)/helper.o testing_compute_forces.o
EXE = testing_compute_forces.x
CC = gcc
CFLAGS = -I $(IPATH) -Wall -Wextra -ffast-math -fomit-frame-pointer -O3
LDLIBS=-lm


default: $(EXE) 

.PHONY: default

$(EXE): $(OBJS)
	$(CC) $^ -o $@

%.o: %.c
	$(CC) -c $(CFLAGS) $(LDLIBS) $< -o $@

testing_compute_forces.o: $(IPATH)/compute_forces.h $(IPATH)/helper.h $(IPATH)/md_struct.h
$(SPATH)/compute_forces.o: $(IPATH)/compute_forces.h $(IPATH)/helper.h $(IPATH)/md_struct.h $(IPATH)/constants.h
$(SPATH)/helper.o: $(IPATH)/helper.h $(IPATH)/md_struct.h $(IPATH)/constants.h

clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean



#test: ./testing_compute_forces.x 
#	./testing_compute_forces.x | tail -n 5 | awk '{print $2 $3 $4}' > a.dat 
#	tail -n 5 compute_forces_export.txt | awk '{printf $2 $3 $4}' > b.dat 
#	cmp a.dat b.dat | echo "Test passed! \n" ||exit 1 
#	rm -f a.dat b.dat
	

