# -*- Makefile -*-

SPATH=../../Objects
IPATH=../../include
#RPATH=..

OBJS = $(SPATH)/kinetic.o TESTU_2atoms.o
EXE = TESTU_2atoms.x
CC = gcc

CFLAGS = -I $(IPATH) -Wall -Wextra -ffast-math -fomit-frame-pointer -O3
LDLIBS=-lm

default: $(EXE)

.PHONY: default

$(EXE): $(OBJS)
	$(CC) $^ -o $@

%.o: %.c
	$(CC) -c $(CFLAGS) $(LDLIBS) $< -o $@

TESTU_2atoms.o: $(IPATH)/kinetic.h $(IPATH)/constants.h $(IPATH)/md_struct.h

$(SPATH)/kinetic.o: $(IPATH)/kinetic.h $(IPATH)/constants.h $(IPATH)/md_struct.h
clean:
	rm -f $(OBJS) $(EXE)

.PHONY: clean
